# @(#) Makefile.disabled 95/05/31 1.2
# DumpStreamCCBs streamtools

TOOL_CLASS =		StreamTools/Source/DumpStreamCCBs

DELIVER_FILES_TO =		${PLATFORM_DIR}/Sources/Streaming/${TOOL_CLASS}
DELIVER_THESE_FILES =	${wildcard *.c *.h *.make *.r}

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic
