# @(#) Makefile 96/04/16 1.5
# Binary tools and data for streaming examples

EXAMPLE_CLASS =		Streaming/Tools_And_Data
EXAMPLE_DATA_REV =	16Apr96
TARGET_DIRECTORY =	${PLATFORM_DIR}/Examples/${EXAMPLE_CLASS}

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
