# @(#) Makefile 95/10/03 1.3
# EZFlixChunkifier streamtools

TOOL_CLASS =		StreamTools/Source/EZFlixChunkifier

DELIVER_FILES_TO =		${PLATFORM_DIR}/Sources/Streaming/${TOOL_CLASS}
DELIVER_THESE_FILES =	${wildcard BuildEZFlixChunkifier *.c *.h *.make *.r *.makemake *.DefaultRules}

include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic
