# @(#) Makefile 96/09/08 1.4

EXAMPLE_CLASS =         System.m2/Requester
EXAMPLE_DATA_REV =      01Sep96
TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Requester
DO_NOT_BUILD_DEPENDS =	1
SELECTED_TARGET_NAMES =	 	StorMgr.utf StorMgr_9.font TextEntry.utf

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata

