# @(#) Makefile 96/06/19 1.7

TARGET_NAME =		StorageManager
TARGET_DIRECTORY =	${REMOTE_DIR}/RomApps
LINK_LIBS =		c
MODULES =		requester frame2d
SIGNED_MODULE =		1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/linkexec
