# @(#) Makefile 96/03/22 1.1
# MPEGAudioChunkifier streamtool

TOOL_CLASS =		StreamTools/Source/MPEGAudioChunkifier

DELIVER_FILES_TO =		${PLATFORM_DIR}/Sources/Streaming/${TOOL_CLASS}
DELIVER_THESE_FILES =	${wildcard *.c *.h *.make *.r}

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic
