# @(#) Makefile 96/07/09 1.15

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/graphics/pipe
DELIVER_THESE_FILES =		\
				box.h		\
				box.inl		\
				col.h		\
				col.inl		\
				geo.h		\
				geo.inl		\
				gfx.h		\
				gp.inl		\
				gpclass.h	\
				gpdata.h	\
				mtx.h		\
				mtx.inl		\
				obj.h		\
				obj.inl		\
				pip.h		\
				pip.inl		\
				print.h		\
				stack.h		\
				stack.inl	\
				surf.h		\
				surf.inl	\
				tex.h		\
				tex.inl		\
				texblend.h	\
				gfxtypes.h	\
				vec.h		\
				vec.inl		\
				vmtx.h

include ${CODEMGR_WS}/ws_root/rules/generic
