# @(#) Makefile 96/01/29 1.4

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/File
PRIVILEGED_MODULE =	1

REQUIRE_HIERARCHICAL_INCLUDES = 1

LOADERTOOL_FLAGS := -Hstack=32768

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec

