# @(#) Makefile 95/08/22 1.8

# Directory build order.
# - "filters" must be built before "debugger".
# - "tcl" must be built before "layout"

include ${CODEMGR_WS}/ws_root/variables/generic

BUILD_IN_FIRST = filters tcl

include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/generic
