# @(#) Makefile 96/02/28 1.4

EXAMPLE_CLASS =			Graphics/Frame2d/Automapper
DELIVER_THESE_FILES =	AutoMapper.c AutoMapper.make
LINK_LIBS =				clt spmath eventbroker c
MODULES =				graphics gstate frame2d

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/linkexec
