# @(#) Makefile 95/10/03 1.4
# MovieToEZFlix streamtools

TOOL_CLASS =            StreamTools/Source/EZFlixChunkifier/Includes

DELIVER_FILES_TO =      ${PLATFORM_DIR}/Sources/Streaming/${TOOL_CLASS}
DELIVER_THESE_FILES =   ${wildcard *.h} 

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic

