# @(#) Makefile 96/09/08 1.3

EXAMPLE_CLASS =         RomApps
EXAMPLE_DATA_REV =      01Sep96
TARGET_DIRECTORY =	${REMOTE_DIR}/RomApps
DO_NOT_BUILD_DEPENDS =	1
SELECTED_TARGET_NAMES =	StorMgr-Title.utf

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata

