# @(#) Makefile 96/10/09 1.4

EXAMPLE_CLASS =			Graphics/Blitter/Blur
LINK_LIBS =				clt eventbroker blitter_utils clt c
MODULES =				gstate graphics blitter iff

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/linkexec
