# @(#) Makefile 96/09/17 1.3

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/Examples/Mercury/include
DELIVER_THESE_FILES =	${wildcard *.h} ${wildcard *.i}

include ${CODEMGR_WS}/ws_root/rules/generic
