# @(#) Makefile 95/09/18 1.3

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/Bench

REQUIRE_HIERARCHICAL_INCLUDES = 1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
