# @(#) Makefile 96/03/11 1.3
# testmpegaudio example data

EXAMPLE_CLASS =		MPEG/TestMPEGAudio
EXAMPLE_DATA_REV =	19Jan96
TARGET_DIRECTORY =  ${REMOTE_DIR}/Tests/MPEG/TestMPEGAudio

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
