# @(#) Makefile 96/01/29 1.4

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/CD-ROM
REQUIRE_HIERARCHICAL_INCLUDES = 1

LOADERTOOL_FLAGS := -Hstack=32768

include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/multilink
