# @(#) Makefile 96/03/20 1.1
# Sound3D patches

DELIVER_FILES_TO =	${REMOTE_DIR}/Examples/Audio/Sound3D
DELIVER_THESE_FILES =	${wildcard *.mp} ${wildcard *.script}
FTP_TRANSFER =		${DELIVER_THESE_FILES:%=${DELIVER_FILES_TO}/%}

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic
