# @(#) Makefile 95/11/07 1.1

ifdef MEMDEBUG
CDEFINES +=		-DMEMDEBUG
endif

INCDIRS =		../includes

include ${CODEMGR_WS}/ws_root/variables/linklib
include ${CODEMGR_WS}/ws_root/rules/generic

all.post: ${OBJS}
