# @(#) Makefile 96/07/08 1.21

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Modules
LOADERTOOL_FLAGS =	-Htype=4 -e main
LINK_LIBS =		spmath clt c
MODULES =		gstate
PRIVILEGED_MODULE =	1
NO_CHDIR_MODULE =	1
MODULE_CALLBACKS =	1
SHOW_MODULE_INFO =	1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
