# @(#) Makefile 95/04/25 1.1

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/streaming
DELIVER_THESE_FILES =	${wildcard *.h}

include ${CODEMGR_WS}/ws_root/rules/generic
