# @(#) Makefile 96/01/29 1.13

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/File
REQUIRE_HIERARCHICAL_INCLUDES = 1

include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/multilink
