# @(#) Makefile 96/03/01 1.8

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Programs
MODULES =		audio
LOADERTOOL_FLAGS = -N

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
