# @(#) Makefile 96/06/04 1.1

INCDIRS 	= ${SRC}/includes ${VCD}/includes
include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/generic
