# @(#) Makefile 96/09/10 1.38

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Tasks
LOADERTOOL_FLAGS =	-Hpri=100 -Hstack=1600
MODULES =		script date batt operator
SIGNED_MODULE =		1
NO_CHDIR_MODULE =	1
SHOW_MODULE_INFO =	1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
