# @(#) Makefile.disabled 95/05/31 1.2
# CtlMaker streamtool

TOOL_CLASS =		StreamTools/Source/CtlMaker

DELIVER_FILES_TO =		${PLATFORM_DIR}/Sources/Streaming/${TOOL_CLASS}
DELIVER_THESE_FILES =	${wildcard *.c *.h *.r *.make CtlMaker_Man_Page}

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic
