# @(#) Makefile 96/07/29 1.3

DELIVER_FILES_TO =      ${PLATFORM_DIR}/includes/tests
DELIVER_THESE_FILES =   3do_scaf.h

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic
