# @(#) Makefile 96/06/25 1.3

TARGET_DIRECTORY =	${MODULE_DIR}
LOADERTOOL_FLAGS =	-Htype=4 -e main
LINK_LIBS =		spmath clt c
MODULES =		graphics gstate
NO_CHDIR_MODULE =	1
SIGNED_MODULE =		1
SHOW_MODULE_INFO =	1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
