
/****************************************************************************
**
**   @(#) basic_machine.h 96/10/16 1.5
**
**  Include file for a Beep Machine
**
** The remainder of this file is generated automatically by compiling a
** Beep Machine. Please do not edit this file.  Your changes will be lost.
****************************************************************************/

#ifndef __KERNEL_TYPES_H
#include <kernel/types.h>
#endif

#define BEEP_MACHINE_NAME "basic.bm"
#define BMGP_AMPLITUDE                  (0xB0010000)
#define BMVP_FILTER_RESONANCE           (0xB0010006)
#define BMVP_AMPLITUDE_RATE             (0xB0C10001)
#define BMVP_LEFT_GAIN                  (0xB0010004)
#define BMVP_RIGHT_GAIN                 (0xB0010005)
#define BMVP_AMPLITUDE                  (0xB0010000)
#define BMVP_ENV_CURRENT                (0xB0010002)
#define BMVP_SAMPLE_RATE                (0xB401000B)
#define BMVP_FILTER_CUTOFF              (0xB001000B)
#define BMVP_LFO_RATE                   (0xB2C1000D)
#define BMVP_FREQ_MOD_DEPTH             (0xB401000E)
#define BMVP_AMP_MOD_DEPTH              (0xB001000F)
#define BMVP_ENV_PHASE                  (0xB0010008)
#define BMVP_ENV_TARGET                 (0xB001000A)
#define BM_NUM_CHANNELS                 (0x00000020)
#define BM_NUM_VOICES                   (0x00000021)
