# @(#) Makefile 96/02/16 1.13

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/beep
DELIVER_THESE_FILES =	beep.h \
		basic_machine.h

include ${CODEMGR_WS}/ws_root/rules/generic
