# @(#) Makefile 96/01/29 1.5

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/File
PRIVILEGED_MODULE =	1
MODULES =		script

LOADERTOOL_FLAGS := -Hstack=32768

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec

