# @(#) Makefile 96/07/09 1.2

TARGET_NAME =           ${DIRNAME}
LINK_LIBS =		clt eventbroker c
MODULES = 		frame2d gstate font graphics

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
