#
# @(#) Makefile 96/03/15 1.1
# DATAChunkify streamtool
#

TOOL_CLASS =		StreamTools/Source/DATAChunkify

DELIVER_FILES_TO =		${PLATFORM_DIR}/Sources/Streaming/${TOOL_CLASS}
DELIVER_THESE_FILES =	${wildcard *.c *.h *.r *.make}

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic
