EXAMPLE_DATA_SOURCE_DIR =	${EXAMPLE_DATA_ARCHIVE_DIR}/mpeg/09feb96
TARGET_DIRECTORY =		${REMOTE_DIR}/Tests/MPEG

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
