# @(#) Makefile 96/09/17 1.4
# score player example data files

TARGET_DIRECTORY =	${REMOTE_DIR}/Examples/Audio/Score
TARGET_NAMES =		${filter %.pimap,${ALLFILES}}
# !!! takes advantage of .pimap support in rules/datafiles

include ${CODEMGR_WS}/ws_root/variables/datafiles
include ${CODEMGR_WS}/ws_root/rules/datafiles
