# @(#) Makefile 96/03/15 1.2
# DataPlayer example data

EXAMPLE_CLASS =		Streaming/DataPlayer
EXAMPLE_DATA_REV =	15March96

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
