# @(#) Makefile 96/09/18 1.1

TARGET_NAME =           ${DIRNAME}
LINK_LIBS = clt blitter_utils spmath c
MODULES =  frame2d gstate graphics blitter iff

include ${CODEMGR_WS}/ws_root/variables/linkexec

TARGET_DIRECTORY = ${REMOTE_DIR}

include ${CODEMGR_WS}/ws_root/rules/linkexec

