# @(#) Makefile 96/03/29 1.10
# PlaySA example data

EXAMPLE_CLASS =		Streaming/PlaySA
EXAMPLE_DATA_REV =	29Mar96

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
