# @(#) Makefile 96/09/04 1.1

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/Script
LINK_LIBS =		c
LOADERTOOL_FLAGS = 	-Hstack=8192
MODULES =		script

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
