# @(#) Makefile 96/08/05 1.16

TARGET_NAME = fonts
EXAMPLE_CLASS = Graphics/Fonts

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/generic
include ${CODEMGR_WS}/ws_root/rules/makeexamples
