# @(#) Makefile 96/04/25 1.13

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/misc
DELIVER_THESE_FILES =	batt.h		\
			compression.h	\
			date.h		\
			debugconsole.h	\
			event.h		\
			frac16.h	\
			iff.h		\
			mpeg.h		\
			mpaudiodecode.h	\
			savegame.h 	\
			script.h

include ${CODEMGR_WS}/ws_root/rules/generic
