# @(#) Makefile 96/01/29 1.11

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/EventBroker
LINK_LIBS =		eventbroker c

include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/multilink
