# @(#) Makefile 96/04/29 1.5

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Programs
PRIVILEGED_MODULE =	1

include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/multilink
