# @(#) Makefile 96/07/01 1.9

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/file
DELIVER_THESE_FILES =	directory.h		\
			directoryfunctions.h	\
			filefunctions.h		\
			fileio.h		\
			filesystem.h		\
			fsutils.h

include ${CODEMGR_WS}/ws_root/rules/generic
