# @(#) Makefile 96/04/22 1.5

DELIVER_FILES_TO =	${PLATFORM_DIR}/Examples
# DELIVER_THESE_FILES =	BuildExamples

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/generic
