# @(#) Makefile 96/07/09 1.4

CDEFINES = -DMEMDEBUG

LINK_LIBS =	clt eventbroker c
MODULES =	graphics gstate frame2d

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec

