# @(#) Makefile 96/06/05 1.1

REQUIRE_HIERARCHICAL_INCLUDES = 1

CDEFINES =              -DEXTERNAL_RELEASE

include ${CODEMGR_WS}/ws_root/variables/linklib
include ${CODEMGR_WS}/ws_root/rules/generic

all.post: ${OBJS}
