# @(#) Makefile 95/06/08 1.5

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Programs

REQUIRE_HIERARCHICAL_INCLUDES = 1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
