# @(#) Makefile 96/09/06 1.1
# EZ3DSound samples

EXAMPLE_CLASS =		Audio/EZ3DSound
EXAMPLE_DATA_REV =	5Sep96

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
