# @(#) Makefile 96/07/03 1.10

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Boot
LOADERTOOL_NAME =	operator.init
STD_MODULES =		filesystem kernel operator
NOSIG_PRIVED_MODULE =	1
NO_CHDIR_MODULE =	1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
