# @(#) Makefile 96/03/08 1.7

TARGET_DIRECTORY = ${REMOTE_DIR}/RomApps
LINK_LIBS     = clt romapp c
MODULES	      = font graphics gstate frame2d
SIGNED_MODULE = 1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
