# @(#) Makefile 96/08/23 1.11

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/kernel
DELIVER_THESE_FILES =	bitarray.h	\
			cache.h		\
			debug.h		\
			device.h	\
			devicecmd.h	\
			driver.h	\
			io.h		\
			item.h		\
			kernelnodes.h	\
			list.h		\
			lumberjack.h	\
			mem.h		\
			msgport.h	\
			nodes.h		\
			operror.h	\
			random.h	\
			semaphore.h	\
			spinlock.h	\
			tags.h		\
			task.h		\
			time.h		\
			types.h		\
			uniqueid.h

include ${CODEMGR_WS}/ws_root/rules/generic
