MAGIC 6
EXPORTS 0=GetDecompressorWorkBufferSize
EXPORTS 1=FeedDecompressor
EXPORTS 2=DeleteDecompressor
EXPORTS 3=CreateDecompressor
EXPORTS 4=GetCompressorWorkBufferSize
EXPORTS 5=FeedCompressor
EXPORTS 6=DeleteCompressor
EXPORTS 7=CreateCompressor
EXPORTS 8=CreateCompressorVA
EXPORTS 9=CreateDecompressorVA
EXPORTS 10=GetCompressorWorkBufferSizeVA
EXPORTS 11=GetDecompressorWorkBufferSizeVA
EXPORTS 12=SimpleCompress
EXPORTS 13=SimpleDecompress

