# @(#) Makefile 96/09/17 1.6
# Data files for anim program

EXAMPLE_CLASS           = Mercury/Examples/data
EXAMPLE_DATA_REV        = 01Sep96
TARGET_DIRECTORY        = ${REMOTE_DIR}/Examples/${EXAMPLE_CLASS}
# SELECTED_TARGET_NAMES		= AnimationEngine.w rush_page.utf rushskt.csf


include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata

