# @(#) Makefile 96/03/19 1.2
# pimap for tj_canon 

EXAMPLE_CLASS =		Audio/Juggler
TARGET_DIRECTORY =	${REMOTE_DIR}/Examples/${EXAMPLE_CLASS}
TARGET_NAMES =		${wildcard *.pimap}

include ${CODEMGR_WS}/ws_root/variables/datafiles
include ${CODEMGR_WS}/ws_root/rules/datafiles
