# @(#) Makefile 96/03/25 1.3
# scrolling clt example data

EXAMPLE_CLASS =         Graphics/CLT/Scrolling
EXAMPLE_DATA_REV =      21mar96

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
