# @(#) Makefile 96/09/05 1.2

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/Math
EXAMPLE_CLASS =         Tests/Math
EXAMPLE_DATA_REV =      01Sep96

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata

