# @(#) Makefile 95/10/16 1.2

EXAMPLE_CLASS =			Graphics/Blitter/TestBlit
LINK_LIBS =			clt eventbroker blitter_utils spmath c
MODULES =			frame2d gstate graphics blitter iff

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/linkexec
