# @(#) Makefile 96/07/09 1.6

TARGET_DIRECTORY =	${REMOTE_DIR}/QuickLook
LINK_LIBS =		clt eventbroker spmath c
MODULES =		graphics gstate frame2d

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
