# @(#) Makefile 96/02/29 1.14

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/audio
DELIVER_THESE_FILES =	atag.h		\
			audio.h		\
			audio_signals.h \
			audio_obsolete.h \
			cobj.h		\
			flex_stream.h	\
			juggler.h	\
			midifile.h	\
			music.h		\
			musicerror.h	\
			parse_aiff.h	\
			patch.h		\
			patchfile.h	\
			score.h		\
			soundplayer.h	\
			soundspooler.h  \
			sound3d.h

include ${CODEMGR_WS}/ws_root/rules/generic
