# @(#) Makefile 96/03/25 1.3
# cltsurface example data

EXAMPLE_CLASS =         Graphics/CLT/CLTSurface
EXAMPLE_DATA_REV =      28mar96

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
