# @(#) Makefile 96/11/27 1.7

DELIVER_FILES_TO =      ${PLATFORM_DIR}/Sources/Blitter_Utils
DELIVER_THESE_FILES =   blend.c mask.c rectangle.c \
			scroll.c utf.c utfattr.c dimensions.c \
			Blitter_Utils.make
TARGET_DIRECTORY =      ${LINK_LIB_DIR}
LIBRARY_IS_PUBLIC =     1

include ${CODEMGR_WS}/ws_root/variables/linklib
include ${CODEMGR_WS}/ws_root/rules/linklib
