# @(#) Makefile 96/04/15 1.10
# VideoPlayer example data

EXAMPLE_CLASS =		Streaming/VideoPlayer
EXAMPLE_DATA_REV =	15Apr96

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
