# @(#) Makefile 96/06/04 1.4

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/loader
DELIVER_THESE_FILES =	loader3do.h	\
			loadererr.h

include ${CODEMGR_WS}/ws_root/rules/generic
