# @(#) Makefile 96/05/17 1.13

TARGET_NAME =		ja.language
TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/International
LOADERTOOL_FLAGS =	-e main
MODULES =		international
PRIVILEGED_MODULE =	1
NO_CHDIR_MODULE =	1
SHOW_MODULE_INFO =	1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
