# @(#) Makefile 96/03/15 1.5
# Text tools and data for streaming examples

EXAMPLE_CLASS =		Streaming/Tools_And_Data
DELIVER_FILES_TO =	${PLATFORM_DIR}/Examples/${EXAMPLE_CLASS}
DELIVER_THESE_FILES =	${wildcard *.script *.worksheet Quotes}

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic
