# @(#) Makefile 96/09/06 1.2
# CoalRiver Song Makefile

EXAMPLE_CLASS =		Audio/Songs/CoalRiver
EXAMPLE_DATA_REV =	3Apr95

include ${CODEMGR_WS}/ws_root/variables/exampledata

# !!! takes advantage of .pimap support in rules/datafiles
TARGET_NAMES +=		${filter %.pimap,${ALLFILES}}

include ${CODEMGR_WS}/ws_root/rules/exampledata
