# @(#) Makefile 95/10/03 1.3
# QTVideoChunkifier streamtools

TOOL_CLASS =		StreamTools/Source/QTVideoChunkifier

DELIVER_FILES_TO =		${PLATFORM_DIR}/Sources/Streaming/${TOOL_CLASS}
DELIVER_THESE_FILES =	${wildcard *.c *.h *.make *.r worksheet.stream}

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic
