# @(#) Makefile 96/03/19 1.17
# music.lib juggler examples

EXAMPLE_CLASS =		Audio/Juggler
LINK_LIBS =		music eventbroker spmath c
MODULES =		audio audiopatchfile iff

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/multilink
