# @(#) Makefile 96/09/25 1.1
# Deliver BuildMercury script to right folder

DELIVER_THESE_FILES =	BuildMercury
DELIVER_FILES_TO =	${PLATFORM_DIR}/Examples/Mercury

include ${CODEMGR_WS}/ws_root/variables/datafiles
include ${CODEMGR_WS}/ws_root/rules/generic

