# @(#) Makefile 95/08/22 1.2

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/ui
DELIVER_THESE_FILES =	icon.h \
			requester.h

include ${CODEMGR_WS}/ws_root/rules/generic
