# @(#) Makefile 96/09/17 1.10
# Data files for anim program

EXAMPLE_CLASS		= Mercury/Examples/data
EXAMPLE_DATA_REV	= 01Sep96
TARGET_DIRECTORY	= ${PLATFORM_DIR}/Examples/${EXAMPLE_CLASS}

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
