# @(#) Makefile 96/07/31 1.16

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Tasks
LOADERTOOL_NAME =	eventbroker
LOADERTOOL_FLAGS =	-Hstack=2048 -Hpri=199
NO_CHDIR_MODULE =	1
SHOW_MODULE_INFO =	1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
