# @(#) Makefile 96/06/14 1.8

EXAMPLE_CLASS =		Graphics/GraphicsFolio
LINK_LIBS =		eventbroker c
MODULES =		graphics

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/multilink
