# @(#) Makefile 95/09/18 1.3

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/File
REQUIRE_HIERARCHICAL_INCLUDES = 1
INCDIRS = .

LINK_LIBS =		c

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
