# @(#) Makefile 96/08/05 1.16

EXAMPLE_CLASS = Graphics/Fonts/Bounce
LINK_LIBS =             clt eventbroker c
MODULES =               graphics font gstate

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/linkexec
