# @(#) Makefile 96/02/21 1.4
# Streaming examples

DELIVER_FILES_TO =	${PLATFORM_DIR}/Examples/Streaming
DELIVER_THESE_FILES =	ds_examples_readme  builddsexamples

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/generic
