# @(#) Makefile 95/10/10 1.3
# AudioChunkifier streamtools

TOOL_CLASS =		StreamTools/Source/AudioChunkifier

DELIVER_FILES_TO =		${PLATFORM_DIR}/Sources/Streaming/${TOOL_CLASS}
DELIVER_THESE_FILES =	${wildcard *.c *.h *.make *.r}

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic
