# @(#) Makefile 95/04/06 1.2
# DrumBox demo data

EXAMPLE_CLASS =		Audio/DrumBox
TARGET_DIRECTORY =	${REMOTE_DIR}/Examples/${EXAMPLE_CLASS}
TARGET_NAMES =		${wildcard *.pimap}

include ${CODEMGR_WS}/ws_root/variables/datafiles
include ${CODEMGR_WS}/ws_root/rules/datafiles

