# @(#)Makefile 96/07/09 1.4

TARGET_DIRECTORY =	${LINK_LIB_DIR}
LIBRARY_IS_PUBLIC =	1

DELIVER_FILES_TO =	${PLATFORM_DIR}/Sources/CLT
DELIVER_THESE_FILES =	autodocs.c \
			cltclear.c \
			cltcopy.c \
			cltdblndattr.c \
			cltglobals.c \
			clttxattr.c \
			clttxload.c \
			cltutils.c

include ${CODEMGR_WS}/ws_root/variables/linklib
include ${CODEMGR_WS}/ws_root/rules/linklib
