# @(#) Makefile 96/06/30 1.5

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/device
DELIVER_THESE_FILES =	cdrom.h \
			mp.h \
			mpegvideo.h \
			proxy.h \
			serial.h \
			te.h

include ${CODEMGR_WS}/ws_root/rules/generic
