# @(#) Makefile 96/11/22 1.32

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Programs
MODULES =		script international date fsutils
NO_CHDIR_MODULE =	1

include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/multilink
