# @(#) Makefile 96/03/12 1.1

EXAMPLE_CLASS =		Miscellaneous/DbgConsole
MODULES =		font gstate graphics
LINK_LIBS =		clt c clt c

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/linkexec
