# @(#) Makefile 96/09/06 1.3
# Zap Makefile

EXAMPLE_CLASS =		Audio/Songs/Zap
EXAMPLE_DATA_REV =	6Apr95

include ${CODEMGR_WS}/ws_root/variables/exampledata

# !!! takes advantage of .pimap support in rules/datafiles
TARGET_NAMES +=		${filter %.pimap,${ALLFILES}}

include ${CODEMGR_WS}/ws_root/rules/exampledata
