char builtinClasses[] =
"# Builtin SDF Classes\n"
"SDFVersion 1.0\n"
"\n"
"define CLASS object {integer dummy }\n"
"\n"
"\n"
"define ENUM bool {\n"
"	true 1\n"
"	false 0\n"
"	yes 1\n"
"	no 0\n"
"	enable 1\n"
"	disable 0\n"
"	on 1\n"
"	off 0\n"
"	}\n"
"\n"
"define ENUM sdf_shade {\n"
"	ambient 1\n"
"	diffuse 2\n"
"	specular 4\n"
"	emissive 8\n"
"	twosided 16\n"
"	}\n"
"\n"
"define ENUM sdf_txgtype {\n"
"	user 0\n"
"	cylindrical 1\n"
"	spherical 2\n"
"	xy 3\n"
"	xz 4\n"
"	yz 5\n"
"	environment 6\n"
"	}\n"
"\n"
"define ENUM sdf_cylpart {\n"
"	sides 1\n"
"	top 2\n"
"	base 4\n"
"	all 8\n"
"	}\n"
"\n"
"define ENUM sdf_blendop {\n"
"	lerp 0\n"
"	mult 1\n"
"	}\n"
"\n"
"define ENUM sdf_wrapmode {\n"
"	clamp 0\n"
"	tile 1\n"
"	}\n"
"\n"
"define ENUM sdf_filter {\n"
"	nearest 0\n"
"	linear 1\n"
"	bilinear 2\n"
"	quasitrilinear 3\n"
"	}\n"
"\n"
"define ENUM sdf_colorsel {\n"
"	constcolor 0\n"
"	constalpha 1\n"
"	texcolor 2\n"
"	texalpha 3\n"
"	primcolor 4\n"
"	primalpha 5\n"
"	}\n"
"\n"
"define ENUM sdf_alphasel {\n"
"	primalpha 4\n"
"	texalpha 3\n"
"	constalpha 1\n"
"	}\n"
"\n"
"define ENUM sdf_pipsel {\n"
"	const 0\n"
"	texture 1\n"
"	colortable 2\n"
"	}\n"
"\n"
"define ENUM sdf_blendout {\n"
"	prim 0\n"
"	texture 1\n"
"	blend 2\n"
"	}\n"
"\n"
"define ENUM sdf_lightkind {\n"
"	directional 0\n"
"	point 1\n"
"	spot 2\n"
"	softspot 3\n"
"	}\n"
"\n"
"define ENUM sdf_camkind {\n"
"	perspective 0\n"
"	orthographic 1\n"
"	}\n"
"\n"
"define ENUM sdf_engcontrol {\n"
"	once 0\n"
"	cycle 1\n"
"	}\n"
"\n"
"define ENUM sdf_engstatus {\n"
"	idle 0\n"
"	active 1\n"
"	}\n"
"\n"
"#The SDF documentation says this class is named 'sdf_engstat' when it is actually named 'sdf_engstatus.'\n"
"\n"
"define ENUM vtx_format {\n"
"	locations 0\n"
"	normals 1\n"
"	colors 2\n"
"	texcoords 4\n"
"	}\n"
"\n"
"define ENUM sdf_vtxorder {\n"
"	clockwise 0\n"
"	counterclockwise 1\n"
"	}\n"
"\n"
"#This class is defined but not used by any SDF classes that I can see. The SDF documentation lists this as 'VertexOrder.'\n"
"\n"
"define ENUM sdf_axis {\n"
"	xaxis 0\n"
"	yaxis 1\n"
"	zaxis 2\n"
"	}\n"
"\n"
"\n"
"define ARRAY shortarray OF short \n"
"define ARRAY floatarray OF float \n"
"define ARRAY color OF float # minlen 3 # maxlen 4 \n"
"define ARRAY colorarray OF color \n"
"define ARRAY point OF float # minlen 3 # maxlen 3 \n"
"define ARRAY pointarray OF point \n"
"define ARRAY texcoord OF float # minlen 2 # maxlen 2 \n"
"define ARRAY box OF float # minlen 6 # maxlen 6 \n"
"define ARRAY transform OF float # minlen 16 # maxlen 16 \n"
"define ARRAY vtx OF float # minlen 3 # maxlen 12 \n"
"define ARRAY vtx_array OF vtx \n"
"define ARRAY texcoordaray OF texcoord \n"
"\n"
"define CLASS material {\n"
"	color ambient\n"
"	color diffuse\n"
"	color emission\n"
"	color specular\n"
"	sdf_shade shadeenable\n"
"	float shine \n"
"}\n"
"\n"
"define CLASS sdf_texgen {\n"
"	sdf_txgtype kind\n"
"	transform transform\n"
"	float urepeat\n"
"	float vrepeat\n"
"	texcoord texscale     \n"
"	texcoord texoffset\n"
"	point translate\n"
"	point rotate\n"
"	point scale \n"
"}\n"
"\n"
"define CLASS vtx_list {\n"
"	vtx_format format\n"
"	vtx_array vertices\n"
"	pointarray locations\n"
"	pointarray normals\n"
"	colorarray colors\n"
"	texcoordaray texcoords \n"
"}\n"
"\n"
"define CLASS trimesh {\n"
"	vtx_list vertexlist\n"
"	shortarray vertexcount\n"
"	shortarray vertexindices \n"
"}\n"
"\n"
"define CLASS quadmesh {\n"
"	vtx_list vertexlist\n"
"	integer verticesperrow\n"
"	integer verticespercolumn \n"
"}\n"
"\n"
"define CLASS geometry {\n"
"	vtx_list vertexlist \n"
"}\n"
"\n"
"define ARRAY matarray OF material \n"
"\n"
"define CLASS cube {\n"
"	float size \n"
"}\n"
"\n"
"define CLASS block {\n"
"	float width\n"
"	float height\n"
"	float depth \n"
"}\n"
"\n"
"define CLASS sphere {\n"
"	float radius\n"
"	float complexity \n"
"}\n"
"\n"
"define CLASS ellipsoid {\n"
"	float x_radius\n"
"	float y_radius\n"
"	float z_radius\n"
"	float complexity \n"
"}\n"
"\n"
"define CLASS torus {\n"
"	float iradius\n"
"	float oradius\n"
"	float complexity \n"
"}\n"
"\n"
"define CLASS cylinder {\n"
"	sdf_cylpart parts\n"
"	float radius\n"
"	float height\n"
"	float complexity \n"
"}\n"
"\n"
"define CLASS truncatedcone {\n"
"	sdf_cylpart parts\n"
"	float top_radius\n"
"	float base_height\n"
"	float complexity \n"
"}\n"
"\n"
"define CLASS character FROM object {\n"
"	bool culling\n"
"	bool visible\n"
"	transform transform\n"
"	color lookat\n"
"	point move\n"
"	point translate\n"
"	point turn\n"
"	point rotate\n"
"	point scale\n"
"	point size\n"
"	float roll\n"
"	float pitch\n"
"	float yaw \n"
"}\n"
"\n"
"define CLASS engine FROM object {\n"
"	float speed\n"
"	float starttime\n"
"	float duration\n"
"	sdf_engstatus status\n"
"	sdf_engcontrol control \n"
"}\n"
"\n"
"define CLASS englink FROM object {\n"
"	object object\n"
"	engine engine \n"
"}\n"
"\n"
"define CLASS texture {\n"
"	file filename \n"
"}\n"
"\n"
"define CLASS piptable {\n"
"	file filename \n"
"}\n"
"\n"
"define CLASS surface {\n"
"	bool autonormals\n"
"	bool autotexcoords\n"
"	bool normalizedtexcoords\n"
"	material material\n"
"	integer matindex\n"
"	integer texindex\n"
"	point normal       # The SDF docs say this is a vector; there's no vector class\n"
"	color color\n"
"	sdf_texgen texgen\n"
"	cube cube\n"
"	block block\n"
"	sphere sphere\n"
"	torus torus\n"
"	ellipsoid ellipsoid\n"
"	cylinder cylinder\n"
"	cylinder cone\n"
"	truncatedcone truncatedcone\n"
"	geometry triangles\n"
"	geometry tristrip\n"
"	geometry trifan\n"
"	geometry polygon\n"
"	geometry points\n"
"	geometry lines\n"
"	quadmesh quadmesh\n"
"	trimesh trimesh \n"
"       }\n"
"\n"
"define CLASS texblend {\n"
"	file filename\n"
"	texture texture\n"
"	piptable pip\n"
"	integer firstlod\n"
"	integer numlod\n"
"	sdf_wrapmode xwrap    # The SDF docs list both these fields as integer\n"
"	sdf_wrapmode ywrap\n"
"	sdf_filter txminfilter\n"
"	sdf_filter txmagfilter\n"
"	sdf_filter txinterfilter\n"
"	integer txpipindexoffset\n"
"	sdf_pipsel txpipcolorsel\n"
"	sdf_pipsel txpipalphasel\n"
"	sdf_pipsel txpipssbsel\n"
"	integer txpipconstssb0\n"
"	integer txpipconstssb1\n"
"	sdf_colorsel txfirstcolor\n"
"	sdf_colorsel txsecondcolor\n"
"	sdf_colorsel txthirdcolor\n"
"	sdf_alphasel txfirstalpha\n"
"	sdf_alphasel txsecondalpha\n"
"	sdf_blendout txcolorout\n"
"	sdf_blendout txalphaout\n"
"	sdf_blendop txblendop       # The SDF docs list this field as sdf_blendout\n"
"	integer txblendcolorssb0\n"
"	integer txblendcolorssb1\n"
"	integer dblenableattrs\n"
"	integer dbldiscard\n"
"	integer dblxwinclipmin\n"
"	integer dblxwinclipmax\n"
"	integer dblywinclipmin\n"
"	integer dblywinclipmax\n"
"	integer dblzcomparecontrol\n"
"	integer dblzxoffset\n"
"	integer dblzyoffset\n"
"	integer dbldsbselect\n"
"	integer dbldsbconst\n"
"	integer dblainputselect\n"
"	integer dblamultcoefselect\n"
"	integer dblamultconstcontrol\n"
"	integer dblamultrtjustify\n"
"	integer dblbinputselect\n"
"	integer dblbmultcoefselect\n"
"	integer dblbmultconstcontrol\n"
"	integer dblbmultrtjustify\n"
"	integer dblaluoperation\n"
"	integer dblfinaldivide\n"
"	integer dbldithermatrixa\n"
"	integer dbldithermatrixb\n"
"	integer dblsrcpixels32bit\n"
"	integer dblsrcbaseaddr\n"
"	integer dblsrcxstride\n"
"	integer dblsrcxoffset\n"
"	integer dblsrcyoffset\n"
"	integer dblrgbconstin\n"
"	integer dblbmultconstssb0\n"
"	integer dblbmultconstssb1\n"
"	integer dblamultconstssb0\n"
"	integer dblamultconstssb1\n"
"	integer dblalpha0clampcontrol\n"
"	integer dblalpha1clampcontrol\n"
"	integer dblalphafracclampcontrol\n"
"	integer dbldestalphaselect\n"
"	integer dbldestalphaconstssb0\n"
"	integer dbldestalphaconstssb1\n"
"	integer pageindex\n"
"	integer subindex\n"
"}\n"
"\n"
"define ARRAY texarray OF texblend \n"
"define ARRAY objarray OF object \n"
"define ARRAY linkarray OF englink \n"
"\n"
"define CLASS group FROM character { }\n"
"\n"
"define CLASS model FROM character {\n"
"	surface surface\n"
"	matarray materials\n"
"	texarray textures \n"
"}\n"
"\n"
"define CLASS light FROM character {\n"
"	sdf_lightkind kind\n"
"	color color\n"
"	float angle\n"
"	float falloff\n"
"	bool enabled \n"
"}\n"
"\n"
"define CLASS camera FROM character {\n"
"	sdf_camkind kind\n"
"	float aspect\n"
"	float height\n"
"	float fieldofview\n"
"	float hither\n"
"	box viewvolume\n"
"	float yon \n"
"}\n"
"\n"
"define CLASS scene FROM object {\n"
"	color backcolor\n"
"	character static\n"
"	character dynamic\n"
"	objarray engines\n"
"	linkarray links\n"
"	camera camera\n"
"	color ambient\n"
"	box viewvolume\n"
"	bool visibility\n"
"	bool autoclip\n"
"	bool autoadjust\n"
"	bool showall \n"
"}\n"
"\0";
