# @(#) Makefile 95/12/18 1.6

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/graphics/clt
DELIVER_THESE_FILES =	\
			clt.h \
			cltmacros.h \
			clttxdblend.h \
			gstate.h

include ${CODEMGR_WS}/ws_root/rules/generic
