# @(#) Makefile 96/03/20 1.3
# sound effect examples

EXAMPLE_CLASS =		Audio/SoundEffects
LINK_LIBS =		music eventbroker spmath c
MODULES =		audio audiopatch audiopatchfile iff

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/multilink
