# @(#) Makefile 96/05/17 1.8

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Errors
LOADERTOOL_FLAGS =	-Htype=17 -e main
NO_CHDIR_MODULE =	1

include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/multilink
