# @(#) Makefile 96/08/13 1.1

TARGET_DIRECTORY =	${HOSTOSBIN}

include ${CODEMGR_WS}/ws_root/variables/hostexec

HINCDIRS    = /usr/include /usr/include/sys ${SRC}/includes

include ${CODEMGR_WS}/ws_root/rules/hostexec
