# @(#) Makefile 96/02/29 1.2

TARGET_NAME =		testBatt
TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/Batt
PRIVILEGED_MODULE = 	1
MODULES =		batt

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
