# @(#) Makefile 96/02/28 1.4

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/graphics/frame2d
DELIVER_THESE_FILES =	f2d.h		\
			frame2d.h	\
			gridobj.h	\
			loadtxtr.h  \
			spriteobj.h

include ${CODEMGR_WS}/ws_root/rules/generic
