# @(#) Makefile 95/07/03 1.5

include ${CODEMGR_WS}/ws_root/variables/hostlib
include ${CODEMGR_WS}/ws_root/rules/hostlib

HOSTCFLAGS += -DMEMMOVE_PRESENT=0 -I.
LINK_LIBS_DIR += .
HOSTLIB_NAME = tcl.a

all.here:

