# @(#) Makefile 95/11/09 1.12

TARGET_NAME =		intltest
TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/International
MODULES =		international

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
