# @(#) Makefile 96/09/06 1.7
# Sound3D samples

EXAMPLE_CLASS =		Audio/Sound3D
EXAMPLE_DATA_REV =	21Mar96

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
