# @(#) Makefile 95/03/17 1.2

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/international
DELIVER_THESE_FILES =	intl.h	\
			jstring.h

include ${CODEMGR_WS}/ws_root/rules/generic
