# @(#) Makefile 96/07/09 1.15

# CDEFINES = -DMEMDEBUG

TARGET_DIRECTORY =	${MODULE_DIR}
LINK_LIBS =		clt spmath c
LOADERTOOL_FLAGS =	-Htype=4 -e main
MODULES =		gstate iff
SIGNED_MODULE =		1
NO_CHDIR_MODULE =	1
SHOW_MODULE_INFO =	1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
