# @(#) Makefile 96/08/19 1.1
# blitter folio example backdrop file

EXAMPLE_CLASS =         Graphics/Blitter
EXAMPLE_DATA_REV =      19aug96

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
