# @(#) Makefile 95/09/18 1.3

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/Math
REQUIRE_HIERARCHICAL_INCLUDES = 1

LINK_LIBS =		spmath c

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
