# @(#) Makefile 95/07/07 1.5
# Tools and data for streaming examples

# Nothing below here needs depends.
DO_NOT_BUILD_DEPENDS =	1

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/generic
