# @(#) Makefile 96/03/20 1.7
# sound player data

EXAMPLE_CLASS =		Audio/Spooling
EXAMPLE_DATA_REV =	20mar96

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
