# @(#) Makefile 95/06/06 1.4
# streamtools

DELIVER_FILES_TO =		${PLATFORM_DIR}/Sources/Streaming
DELIVER_THESE_FILES =	BuildStreamTools

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/generic
