
/****************************************************************************
**
**  @(#) machine_preamble.h 96/02/29 1.2
**
**  Include file for a Beep Machine
**
** The remainder of this file is generated automatically by compiling a
** Beep Machine. Please do not edit this file.  Your changes will be lost.
****************************************************************************/

#ifndef __KERNEL_TYPES_H
#include <kernel/types.h>
#endif

