# @(#) Makefile 96/06/10 1.1

TARGET_DIRECTORY = ${REMOTE_DIR}/RomApps
LINK_LIBS     = clt eventbroker romapp c
MODULES	      = font graphics gstate frame2d
REQUIRE_HIERARCHICAL_INCLUDES = 1
PRIVILEGED_MODULE =     1
SIGNED_MODULE = 1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec

