# @(#) Makefile 95/04/06 1.1
# System AIFF files.

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Audio/aiff

include ${CODEMGR_WS}/ws_root/variables/datafiles
include ${CODEMGR_WS}/ws_root/rules/datafiles

