# @(#) Makefile 96/01/26 1.14

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Tasks
TARGET_NAME=		romapplauncher
LINK_LIBS =		romapp c
MODULES =		script
REQUIRE_HIERARCHICAL_INCLUDES = 1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec

