# @(#) Makefile 96/02/05 1.3

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Programs
PRIVILEGED_MODULE =	1
NO_CHDIR_MODULE =	1

include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/multilink
