# @(#) Makefile 95/08/23 1.6

EXAMPLE_CLASS =		Kernel
LINK_LIBS =		c

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/multilink
