# @(#) Makefile 96/09/06 1.2
# Generic makefile to deliver data files to Examples/Graphics/...

EXAMPLE_CLASS =         Graphics/Models
EXAMPLE_DATA_REV =      01Sep96
DO_NOT_BUILD_DEPENDS =  1

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata

