# @(#) Makefile.disabled 95/09/18 1.7

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/Audio
LINK_LIBS =		music audio eventbroker file spmath c
# INCDIRS =		${SRC}/tests/audio/e3master

ifdef TEST
    CDEFINES +=		-DMUSIC_TEST_MODE
endif

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec

