# @(#) Makefile 95/11/22 1.4
# EZFlixChunkifier streamtools

BULLET = "__"
TOOL_CLASS =		StreamTools/Source/EZFlixChunkifier/${BULLET}EZFlixEncoder

DELIVER_FILES_TO =		${PLATFORM_DIR}/Sources/Streaming/${TOOL_CLASS}
DELIVER_THESE_FILES =	${wildcard *.c *.cp *.h *.make *.r}

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic
