# @(#) Makefile 96/01/26 1.14

EXAMPLE_CLASS =		Miscellaneous/Compression
LOADERTOOL_FLAGS =	-Hstack=4000
LINK_LIBS =		c
MODULES =		compression

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/linkexec
