# @(#) Makefile 95/06/28 1.2
# Example songs

DO_NOT_BUILD_DEPENDS =	1

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/generic
