# @(#) Makefile 96/07/23 1.9

EXAMPLE_CLASS =		Graphics/CLT/GSquare
LINK_LIBS =		clt spmath eventbroker c
MODULES =		graphics gstate

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/linkexec
