# @(#) Makefile 96/02/21 1.4
# playfast example data

EXAMPLE_CLASS =		MPEG/PlayFast
EXAMPLE_DATA_REV =	16oct95

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
