# @(#) Makefile 96/09/19 1.1
# Get archived mercury data to the remote folder.

EXAMPLE_CLASS =		Mercury/Examples/data
EXAMPLE_DATA_REV =	01Sep96
TARGET_DIRECTORY =      ${REMOTE_DIR}/Examples/Mercury/Examples/bigcircle
SELECTED_TARGET_NAMES =	three.utf twelve.utf sky.utf

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata

