# @(#) Makefile 96/02/28 1.1

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Programs
TARGET_NAME = clock
PRIVILEGED_MODULE =	1
MODULES =		batt

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
