# @(#) Makefile 96/06/04 1.1

TARGET_DIRECTORY  =	${LINK_LIB_DIR}
LIBRARY_IS_PUBLIC =	1
TARGET_NAME =		libvcddsutils.a
REQUIRE_HIERARCHICAL_INCLUDES = 1

CDEFINES =              -DEXTERNAL_RELEASE
INCDIRS  =		${VCD}/includes
include ${CODEMGR_WS}/ws_root/variables/linklib
include ${CODEMGR_WS}/ws_root/rules/linklib
