# @(#) Makefile 96/02/23 1.6

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/CD-ROM
PRIVILEGED_MODULE =	1

REQUIRE_HIERARCHICAL_INCLUDES = 1

LINK_LIBS =		eventbroker c
LOADERTOOL_FLAGS := -Hstack=32768

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec

