# @(#) Makefile 96/01/30 1.10

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/Kernel
LINK_LIBS =		spmath c
REQUIRE_HIERARCHICAL_INCLUDES = 1

include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/multilink
