# @(#) Makefile.disabled 95/05/31 1.3
# DumpAIFF streamtools

TOOL_CLASS =         StreamTools/Source/DumpAIFF
 
DELIVER_FILES_TO =      ${PLATFORM_DIR}/Sources/Streaming/${TOOL_CLASS}
DELIVER_THESE_FILES =   ${wildcard *.c *.h *.make *.r}
 
include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic
