# @(#) Makefile 95/11/22 1.8

DELIVER_FILES_TO =      ${PLATFORM_DIR}/Sources/Streaming
DELIVER_THESE_FILES =   BuildAllM2DS		\
						BuildM2DS			\
						CompareDSVersions	\
 						#BuildM2DSShuttle

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/generic
