# @(#) Makefile 96/04/04 1.1
# MPEGVideoChunkifier streamtool

TOOL_CLASS =		StreamTools/Source/MPEGVideoChunkifier

DELIVER_FILES_TO =		${PLATFORM_DIR}/Sources/Streaming/${TOOL_CLASS}
DELIVER_THESE_FILES =	${wildcard *.c *.h *.make *.r}

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic
