# @(#) Makefile 96/09/17 1.30
# Makefile to trigger all source directories to be built.

DELIVER_FILES_TO =	${PLATFORM_DIR}/Examples/Mercury/lib
DELIVER_THESE_FILES =	autodocs.c

include ${CODEMGR_WS}/ws_root/variables/generic

default: all

include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/generic

