# @(#) Makefile 96/09/24 1.10

EXAMPLE_CLASS =		FileSystem

EXTRA_SRC = ${SRC}/programs/file/ls.c \
	    ${SRC}/programs/file/type.c \
	    ${SRC}/programs/file/walker.c

MODULES =		date

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/multilink
include ${CODEMGR_WS}/ws_root/rules/extrasrc
