# @(#) Makefile 95/05/12 1.2

EXTRA_SRC = ${SRC}/folios/compression/compress.c

include ${CODEMGR_WS}/ws_root/variables/hostexec

HOSTCFLAGS += -DNO_PORTFOLIO
HINCDIRS    = ${SRC}/includes ${SRC}/folios/compression

include ${CODEMGR_WS}/ws_root/rules/hostexec
include ${CODEMGR_WS}/ws_root/rules/extrasrc
