# @(#) Makefile 96/02/21 1.3

EXAMPLE_CLASS = MPEG/Photo

LINK_LIBS =	eventbroker c
MODULES =	graphics
NO_CHDIR_MODULE =   1

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/linkexec
