# @(#) Makefile 95/11/09 1.5

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Programs
MODULES = 		iff
NO_CHDIR_MODULE =	1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
