# @(#) %M 96/02/21 1.4
# Example models data

EXAMPLE_CLASS		= Graphics/Models
EXAMPLE_DATA_REV	= 5jan96

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
