# @(#) Makefile 95/07/05 1.5

include ${CODEMGR_WS}/ws_root/variables/generic

default:
	${RM} ./graphics
	${SLN} ${SRC}/includes/graphics .

DO_NOT_BUILD_IN =	graphics

include ${CODEMGR_WS}/ws_root/rules/extrasrc
include ${CODEMGR_WS}/ws_root/rules/generic
