# @(#) Makefile 96/03/20 1.5
# Beep folio examples

EXAMPLE_CLASS =		Audio/Beep
LINK_LIBS =		music eventbroker spmath c
MODULES =		beep iff

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/multilink
