# @(#) Makefile 95/11/01 1.3
# EZFlixPlayer example data

EXAMPLE_CLASS =		Streaming/EZFlixPlayer
EXAMPLE_DATA_REV =	09Sep95

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata
