# @(#) Makefile 95/09/18 1.2

TARGET_DIRECTORY =	${REMOTE_DIR}/Tests/Math

include ${CODEMGR_WS}/ws_root/variables/multilink
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/multilink
