# @(#) Makefile 96/07/09 1.15

include ${CODEMGR_WS}/ws_root/variables/generic

DELIVER_FILES_TO =	${PLATFORM_DIR}/includes/graphics
DELIVER_THESE_FILES =	\
			bitmap.h	\
			view.h		\
			projector.h	\
			graphics.h	\
			font.h		\
			blitter.h

include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/generic
