# @(#) Makefile 96/02/29 1.13

TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/Programs
PRIVILEGED_MODULE =	1
MODULES =		international batt

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
