# @(#) Makefile 95/10/20 1.1

DELIVER_THESE_FILES =	hfdata
DELIVER_FILES_TO =		${REMOTE_DIR}/Examples/Graphics/CLT/height_field

include ${CODEMGR_WS}/ws_root/variables/generic
include ${CODEMGR_WS}/ws_root/rules/generic

