# @(#) Makefile.disabled 95/12/08 1.7

CDEFINES =              -DEXTERNAL_RELEASE

DELIVER_FILES_TO =      ${PLATFORM_DIR}/Sources/Streaming/Libs/Subscribers/ProtoSubscriber
DELIVER_THESE_FILES =   protochannels.c		\
                    	protosubscriber.c	\
                    	ProtoSubscriber.make

include ${CODEMGR_WS}/ws_root/variables/linklib
include ${CODEMGR_WS}/ws_root/rules/generic

all.post: ${OBJS}
