# @(#) Makefile.disabled 96/02/28 1.8

include ${CODEMGR_WS}/ws_root/variables/gfxapp

LINK_LIBS =             audiodemo music frame_utils framework bsdf framework pipeline bsdf clt spmath eventbroker ${MEMDEBUG_LIB} c
MODULES =               audiopatch audio font graphics gstate frame2d

include ${CODEMGR_WS}/ws_root/rules/gfxapp
