# @(#)Makefile 95/03/23 1.2


include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/variables/gfxapp
TARGET_DIRECTORY =  ${REMOTE_DIR}/Tests/MPEG
include ${CODEMGR_WS}/ws_root/rules/gfxapp

