# @(#) Makefile 96/05/23 1.10

TARGET_DIRECTORY =	${MODULE_DIR}
LOADERTOOL_FLAGS =	-Htype=4 -e main
LINK_LIBS        =	spmath clt c
MODULES		 =	iff graphics gstate frame2d
PRIVILEGED_MODULE = 	1
NO_CHDIR_MODULE =	1
MODULE_CALLBACKS =	1
SHOW_MODULE_INFO =	1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
