# @(#) Makefile 96/06/27 1.6

TARGET_DIRECTORY  =	${LINK_LIB_DIR}
LIBRARY_IS_PUBLIC =	1

DELIVER_FILES_TO =      ${PLATFORM_DIR}/Sources/EventUtility
DELIVER_THESE_FILES =   ${wildcard *.c}

include ${CODEMGR_WS}/ws_root/variables/linklib
include ${CODEMGR_WS}/ws_root/rules/linklib
