# @(#) Makefile 96/09/06 1.2


EXAMPLE_CLASS =         Graphics/CLT/height_field
EXAMPLE_DATA_REV =      01Sep96
DO_NOT_BUILD_DEPENDS =  1

include ${CODEMGR_WS}/ws_root/variables/exampledata
include ${CODEMGR_WS}/ws_root/rules/exampledata

