# @(#) Makefile.disabled 95/08/23 1.3
# CoalRiver demo

EXAMPLE_CLASS =		Audio/CoalRiver
LINK_LIBS =		music audio graphics eventbroker file spmath c

include ${CODEMGR_WS}/ws_root/variables/makeexamples
include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/subtree
include ${CODEMGR_WS}/ws_root/rules/makeexamples
include ${CODEMGR_WS}/ws_root/rules/linkexec
