# @(#) Makefile 96/09/23 1.6

TARGET_NAME =		${DIRNAME}.fs
TARGET_DIRECTORY =	${REMOTE_DIR}/System.m2/FileSystems
LOADERTOOL_FLAGS =	-Hstack=2048 -Hpri=210 -e main
PRIVILEGED_MODULE =	1
NO_CHDIR_MODULE =	1
SHOW_MODULE_INFO =	1

include ${CODEMGR_WS}/ws_root/variables/linkexec
include ${CODEMGR_WS}/ws_root/rules/linkexec
