# @(#) Makefile 96/03/21 1.3

TARGET_DIRECTORY =	${REMOTE_DIR}/Examples/Audio/Sound3D/SeeSound
DELIVER_FILES_TO =	${PLATFORM_DIR}/Examples/Audio/Sound3D/SeeSound
DELIVER_THESE_FILES =	${wildcard *.sdf}

include ${CODEMGR_WS}/ws_root/variables/datafiles
include ${CODEMGR_WS}/ws_root/rules/datafiles
